name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-pypi-github:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/nonebot-plugin-send-anything-anywhere
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v5
        with:
          name: Release ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish PyPI and Github
        run: |
          poetry build
          gh release upload --clobber ${{ env.TAG_NAME }} dist/*.tar.gz dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish pypi
        uses: pypa/gh-action-pypi-publish@release/v1
